In [328]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


## IF 
```python
a = np.array([[1,2,3]])
``` 
## then a will be of dim 2

In [329]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [330]:

# Get Dimension
a.ndim

1

In [331]:
a.shape

(3,)

In [332]:
# Get Type
a.dtype

dtype('int32')

In [333]:
# Get Size
a.itemsize

4

In [334]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

BEWARE: THINGS START FROM O, NOT FROM 1

In [335]:
a[1,1]

9

In [336]:
a[0,-1]

7

In [337]:
a[:,2] #==>meaningful

array([ 3, 10])

### a[:2] ==> **Umeaningful**

In [338]:
a[0,:] #0th row and all columns of that row

array([1, 2, 3, 4, 5, 6, 7])

In [339]:
a[1:]     # a[n:]   ==>    select all rows starting with index 'n'

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [340]:
k=a[:, 2]     
k_str = ' '.join(map(str, k))
result = 'Result=' + k_str

print(result)
print(k.shape)
print(k.ndim)

Result=3 10
(2,)
1


In [341]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## ``SOMETHING FANCY``

In [342]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

## ``IMP: End index not included``

In [343]:
a[0, 1:-1:2]

array([2, 4, 6])

In [344]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


see that cell 1,5 number is 20 now and entire column with index 2 is [1,2]

In [345]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [346]:
b.shape  #NOTE: 2channels,2rows,2columns

(2, 2, 2)

b is 3d vector

In [347]:
b.ndim

3

In [348]:
b[0,1,1]

4

In [349]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [350]:
np.ones((4,2,2), dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [351]:
np.ones((4,2,2), dtype='float64')


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [352]:
# Any other number
l=np.full((2,5,2), 99)
l

array([[[99, 99],
        [99, 99],
        [99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99],
        [99, 99],
        [99, 99]]])

In [353]:
# Any other number (full_like)
np.full_like(l, 4)  #make the matrix with all 4 and dimensons same as l

array([[[4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4]]])

In [354]:
# Random decimal numbers
np.random.rand(4,2)     

array([[0.91789842, 0.82560036],
       [0.06579707, 0.07714519],
       [0.87014283, 0.48804941],
       [0.6449028 , 0.6777834 ]])

### ``BY DEFAULT IT POPULATES WITH FLOAT NUMBERS BETWEEN 0 & 1``

In [355]:
np.random.randint(-4,8, size=(3,3))


array([[ 6,  1, -4],
       [ 3, -2, -1],
       [ 7,  4,  2]])

In [356]:
# The identity matrix
np.identity(5)     #dim = 5*5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [357]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [358]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3 )
print(r1)      #sequential repetition

[1 1 1 2 2 2 3 3 3]


In [359]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1 )
print(r1)        #horizontal repetition

[[1 1 1 2 2 2 3 3 3]]


In [360]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [361]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [362]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [363]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [364]:
a = np.array([1,2,3.1428,4])

In [365]:
a-2

array([-1.    ,  0.    ,  1.1428,  2.    ])

In [366]:
b = np.array([1,0,1,0])
a + b

array([2.    , 2.    , 4.1428, 4.    ])

In [367]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.99999927, -0.65364362])

In [368]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [369]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

# np.hstack((h1,h2))

In [370]:
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [371]:
np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [372]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


CONVERTING txt FILE INTO MATRIX

In [373]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [374]:
filedata.shape

(3, 18)

In [375]:
filedata.reshape(3,18)

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [376]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])